### ISSUE TITLE
测试问题test_3_dataset.py

### ISSUE THREAD

**Issue by Winkness** [LianYi233/Trans-CMLT#1]
我使用test_3_dataset.py测试结果，得到如下结果：
172.0	191.0	16	15
tensor(168.5649, device='cuda:0', grad_fn=<SubBackward0>)	tensor(187.3681, device='cuda:0', grad_fn=<SubBackward0>)	tensor(29.5128, device='cuda:0', grad_fn=<SelectBackward>)	tensor(27.5543, device='cuda:0', grad_fn=<SelectBackward>)
tensor(163.6086, device='cuda:0', grad_fn=<SubBackward0>)	tensor(179.3883, device='cuda:0', grad_fn=<SubBackward0>)	tensor(53.1051, device='cuda:0', grad_fn=<SelectBackward>)	tensor(49.2499, device='cuda:0', grad_fn=<SelectBackward>)
tensor(154.1581, device='cuda:0', grad_fn=<SubBackward0>)	tensor(164.2183, device='cuda:0', grad_fn=<SubBackward0>)	tensor(97.9674, device='cuda:0', grad_fn=<SelectBackward>)	tensor(92.4567, device='cuda:0', grad_fn=<SelectBackward>)
tensor(147.2324, device='cuda:0', grad_fn=<SubBackward0>)	tensor(137.6403, device='cuda:0', grad_fn=<SubBackward0>)	tensor(185.2234, device='cuda:0', grad_fn=<SelectBackward>)	tensor(176.8567, device='cuda:0', grad_fn=<SelectBackward>)
tensor(118.0862, device='cuda:0', grad_fn=<SubBackward0>)	124.0	tensor(353.2392, device='cuda:0', grad_fn=<SelectBackward>)	248
tensor(139.3141, device='cuda:0', grad_fn=<SubBackward0>)	124.0	473	248
tensor(230.0239, device='cuda:0', grad_fn=<SubBackward0>)	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
236.5	124.0	473	248
...
请问这种是什么原因呢？

**Comment by LianYi233** [comment]
每一帧坐标都是一样的，可能是加载了随机权重？先训练好网络再测试吧：）

**Comment by Winkness** [comment]
了解了，感谢！

**Comment by Wei-Peng-fei** [comment]
test_3_dataset.py的create_dataset里面的LaSOTDataset的json文件你有吗？

**Comment by laisimiao** [comment]
@LianYi233 没有官方的模型可以下载吗
