### ISSUE TITLE
关于数据读取问题

### ISSUE THREAD

**Issue by Wei-Peng-fei** [LianYi233/Trans-CMLT#4]
在HOT2023的数据集中，其文件结构如下，

![image](https://github.com/user-attachments/assets/ec569755-952d-40ed-9b30-e4f6693b27f6)
但是其中/HSITRACKING/training/HSI-NIR/basketball1中的图片如下，是一个png图片，请问你怎么处理这种图片，我在您的代码中只看到您加载了FlaseColor数据并未加载HSI-NIR数据
![0001](https://github.com/user-attachments/assets/9b962587-d64f-45c4-9741-2381bdb79340)

**Comment by LianYi233** [comment]
HSI图片可以用官方提供的X2Cube函数读取。
在/ltr/data/image_loader.py中，if use_hsi这里，加载了HSI图片级联在伪彩色图后面。
