### ISSUE TITLE
关于数据的一些疑问

### ISSUE THREAD

**Issue by Wei-Peng-fei** [LianYi233/Trans-CMLT#5]
![image](https://github.com/user-attachments/assets/f2838335-fc63-4f43-b647-b63219e7fa2b)
很抱歉，再次打扰你，由于我是一个研0的学生因此对部分内容没法完全理解，特此发问。在文件路径这里，我发现你有NIR和VIS 但是在hot2024数据集中，还有RedNIR这个数据，的在ltr/data_specs文件夹下给出来三个数据集的样本名称，但是跟HOT2024的数据集中的样本却对不上。

**Comment by LianYi233** [comment]
在2023数据集的实验中，我是将NIR和RedNIR合并为同一个子集训练的；
你可以用os.listdir自己生成一个HOT2024样本名称的列表。

**Comment by Wei-Peng-fei** [comment]
好的，但我注意到在ltr/data_specs中，VIS_train_split中您提供了55个类别，但在VOT2024中VIS数据集有111个类别，我不明白这是为什么请问能解释一下吗？
![image](https://github.com/user-attachments/assets/adc6d049-2b42-4a52-84c2-5905583933cd)
![image](https://github.com/user-attachments/assets/134abdb5-09cb-4e8f-9935-f8f0e3cb7282)

**Comment by Wei-Peng-fei** [comment]
关于数据集，您应该使用的是HOT2024吧？因为在HOT官网上2023数据集其实和2020数据集一样，当时数据集中并未有NIR、VIS、REDNIR。VOT2023数据集：https://www.hsitracking.com/hot2023/  VOT2024数据集：https://www.hsitracking.com/contest/

**Comment by LianYi233** [comment]
去年的数据集和今年的一样，有NIR、RedNIR、VIS三类和对应的FalseColor图，其中VIS有55个视频。刚才打开你的链接看了一下，是2020的，和去年下载的不一样

**Comment by Wei-Peng-fei** [comment]
好的，十分感谢，是我误解了您，请问您能给一下您的文件结构吗？我在考虑是否需要重写一下dataloader部分。├── HSI-NIR
├── HSI-NIR-FalseColor
├── HSI-NIR.txt
├── HSI-RedNIR
├── HSI-RedNIR-FalseColor
├── HSI-VIS
├── HSI-VIS-FalseColor
├── readme_HSI-VIS-FlaseColor.txt
└── readme_HSI-VIS.txt

**Comment by Wei-Peng-fei** [comment]
好的，十分感谢，是我误解了您，请问您能给一下您的文件结构吗？我在考虑是否需要重写一下dataloader部分。├── HSI-NIR
├── HSI-NIR-FalseColor
├── HSI-NIR.txt
├── HSI-RedNIR
├── HSI-RedNIR-FalseColor
├── HSI-VIS
├── HSI-VIS-FalseColor
├── readme_HSI-VIS-FlaseColor.txt
└── readme_HSI-VIS.txt

**Comment by Wei-Peng-fei** [comment]
好的，十分感谢，是我误解了您，下面是我的文件结构，请问我的文件结构和您的文件结构是否一致呢？我在考虑是否需要重写dataloader部分。请您额外注意数据中HSI和FalseColor的图片后缀，十分感谢。
├── HSI-NIR
.........|——basketball
..................|——00001.png
..................|——................
.........|................................
├── HSI-NIR-FalseColor
.........|——basketball
..................|——00001.jpg
..................|——................
.........|................................
├── HSI-RedNIR
├── HSI-RedNIR-FalseColor
├── HSI-VIS
├── HSI-VIS-FalseColor

**Comment by LianYi233** [comment]
> 好的，十分感谢，是我误解了您，下面是我的文件结构，请问我的文件结构和您的文件结构是否一致呢？我在考虑是否需要重写dataloader部分。请您额外注意数据中HSI和FalseColor的图片后缀，十分感谢。 ├── HSI-NIR .........|——basketball ..................|——00001.png ..................|——................ .........|................................ ├── HSI-NIR-FalseColor .........|——basketball ..................|——00001.jpg ..................|——................ .........|................................ ├── HSI-RedNIR ├── HSI-RedNIR-FalseColor ├── HSI-VIS ├── HSI-VIS-FalseColor

对的，就是这样的结构

**Comment by Wei-Peng-fei** [comment]
十分感谢，但还需再叨扰您一下，我在训练的时候发现GPU并未满载工作，请问您那是否存在同样的情况？（device 0 GPU型号3090，数据存在固态上，CPU 12代i9 12900K，请问您在训练的时候是否存在这种情况呢，下图是nvtop，蓝线是GPU计算，黄线是显存占用）
![image](https://github.com/user-attachments/assets/b56e5471-2e47-43f4-87b3-48a573bca620)

**Comment by Wei-Peng-fei** [comment]
十分感谢您！谢谢你，学姐！xd，yyds
